version: '3'
services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: datadik
    container_name: appdatadik
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - datadik
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: nginxdatadik
    restart: unless-stopped
    tty: true
    ports:
      - "8090:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - datadik

  #MySQL Service
  db:
    image: mysql
    container_name: dbdatadik
https://stackoverflow.com/questions/49019652/not-able-to-connect-to-mysql-docker-from-local#:~:text=db%3A%0A%20%20%20%20image%3A%20mysql-,command%3A%20mysqld,-%2D%2Ddefault%2Dauthentication%2Dplugin
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: datadik
      # MYSQL_USER: root
      MYSQL_PASSWORD: datadik
      MYSQL_ROOT_PASSWORD: datadik
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - datadik

# phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8990:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: datadik
    networks:
      - datadik

  #Docker Networks
networks:
  datadik:
    driver: bridge
  #Volumes
volumes:
  lbdata:
    driver: local
